### PR TITLE
Add support for LMPOP

### PR DESCRIPTION
**Pull request by SoulPancake**
Adding command and command test for LMPOP command.

### CODE REVIEW

**Comment by monkey92t** [comment]
You should handle redis-server response data correctly.

**Comment by SoulPancake** [comment]
@monkey92t I'm a little confused about decoding the RESP array parts , In the other tests with array reply it looked straightforward however here the string slice is in that format , Do you have any suggestions for writing meaningful tests for that part? Is this something I should refer to ? https://redis.io/docs/reference/protocol-spec/#resp-arrays:~:text=the%20reply%20object).-,RESP%20Arrays,-Clients%20send%20commands

**Comment by monkey92t** [comment]
@SoulPancake 

You should pay attention to the return value of the command:

```shell
LMPOP 2 mylist mylist2 right count 3
*2
$6
mylist
*3
$3
one
$3
two
$5
three
```

**Comment by monkey92t** [comment]
The `lmpop` command responds not to a slice, but to a complex structure, an example in the go structure:

```go
type Data struct {
         key string
         Element [] string
}
```

**Comment by SoulPancake** [comment]
@monkey92t So I should change my approach from a stringSliceCmd to a custom struct correct?

**Comment by SoulPancake** [comment]
> The LMPOP command responds not to a slice, but to a complex structure

Do we already have a struct for running such complex structure command responses that I can re-use or do I need to create it as well?

**Comment by monkey92t** [comment]
> > The LMPOP command responds not to a slice, but to a complex structure
> 
> Do we already have a struct for running such complex structure command responses that I can re-use or do I need to create it as well?

Yes, when you find that there is no suitable data structure in `command.go`, you should create a new `CMD`.

**Comment by monkey92t** [comment]
@SoulPancake 

If you need a test environment, welcome to use the tool I made: "https://github.com/monkey92t/grte"  😁

**Comment by SoulPancake** [comment]
@monkey92t Thanks a lot and sorry for bothering so many times, I am new to this I am trying to learn and help.
I will close this and re-open it after I've figured it out.

**Comment by monkey92t** [comment]
@SoulPancake 

OK, "https://github.com/monkey92t/grte" This tool is relatively simple, but use it to do some simple testing work, the following is an example:

```go
monkey@MonkeyiMac redis % grte go test ./...                                                                           
[go-redis]  🐳 Prepare docker image ==> goredis/grte:v9
[go-redis]  🐳 Use image cache, ID ==> sha256:f4a6149b55e000ed40b5a68041615e7223b52119178d6ec4190f4714b8b88a49
[go-redis]  🐳 Create docker container...
[go-redis]  🐳 ContainerID: 28f0d7c79293a106bf0c54a76ea3a4ede41ee052332fe49263e24f8609a2aa7d
[go-redis]  🐳 WorkDir: /Users/monkey/Desktop/redis
[go-redis]  🐳 Command: [go test ./...]
go: downloading github.com/bsm/gomega v1.26.0
go: downloading github.com/bsm/ginkgo/v2 v2.7.0
go: downloading github.com/cespare/xxhash/v2 v2.2.0
go: downloading github.com/dgryski/go-rendezvous v0.0.0-20200823014737-9f7001d12a5f
go: downloading github.com/stretchr/testify v1.8.1
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading gopkg.in/yaml.v3 v3.0.1
ok  	github.com/redis/go-redis/v9	103.717s
ok  	github.com/redis/go-redis/v9/internal	0.007s
ok  	github.com/redis/go-redis/v9/internal/hashtag	0.008s
ok  	github.com/redis/go-redis/v9/internal/hscan	0.009s
ok  	github.com/redis/go-redis/v9/internal/pool	1.589s
ok  	github.com/redis/go-redis/v9/internal/proto	0.009s
?   	github.com/redis/go-redis/v9/internal/rand	[no test files]
?   	github.com/redis/go-redis/v9/internal/util	[no test files]
[go-redis]  ✅  Success!
```

If you want to test other directories:

```go
monkey@MonkeyiMac redis % cd internal/pool
monkey@MonkeyiMac pool % grte go test ./...
[go-redis]  🐳 Prepare docker image ==> goredis/grte:v9
[go-redis]  🐳 Use image cache, ID ==> sha256:f4a6149b55e000ed40b5a68041615e7223b52119178d6ec4190f4714b8b88a49
[go-redis]  🐳 Create docker container...
[go-redis]  🐳 ContainerID: b094b74369998707dbcfeb128827a14dace8af67783460b5cbaa2d27d922eb45
[go-redis]  🐳 WorkDir: /Users/monkey/Desktop/redis/internal/pool
[go-redis]  🐳 Command: [go test ./...]
ok  	github.com/redis/go-redis/v9/internal/pool	1.529s
[go-redis]  ✅  Success!
monkey@MonkeyiMac pool % 
```

**Comment by SoulPancake** [comment]
Thanks a lot @monkey92t

**Comment by SoulPancake** [comment]
@monkey92t The test failure that I can see seems to be unrelated from the implementation or test, Can you take a look at it once?

**Comment by monkey92t** [comment]
> @monkey92t The test failure that I can see seems to be unrelated from the implementation or test, Can you take a look at it once?
The `[]interface{}` type is not convenient to use.

**Comment by SoulPancake** [comment]
@monkey92t I had referred to https://github.com/redis/go-redis/blob/08b4cc5f4ba87d5eaf9bd30b8e4ae97a7dac3dbc/commands_test.go#L2046 as they were using a similar approach,
To be able to use SliceCmd this was an approach but I guess now a custom struct is a nicer approach?

**Review by monkey92t — APPROVED** [review]
Looks good.

**Pull request merged**
