### PR TITLE
fix ConnPool race in newConn

### PR DESCRIPTION
**Pull request by OlegStotsky**
Currently there is a race in newConn. This means that any code that uses this client will fail tests with -race flag enabled. This PR fixes this.

### CODE REVIEW

**Comment by OlegStotsky** [comment]
@ofekshenawa please take a look

**Comment by Aden-Q** [comment]
@OlegStotsky You should mention my issue [here](https://github.com/redis/go-redis/issues/2876) (if you saw it). And I don't think it's the correct way to fix the issue. Even though it can protect the variable to be mutated while being read. There still can be interleaving execution flows, causing some errors on the semantic level (for example, read the value in one goroutine, afterwards it is updated by another goroutine). I think we need to we protect the full scope of the critical section, instead of doing: lock-unlock, then lock-unlock again.

**Comment by OlegStotsky** [comment]
@Aden-Q I've added another check after we acquire the mutex again. Should be correct now.

**Comment by OlegStotsky** [comment]
@vmihailenco could you take a look please

**Review by ofekshenawa — APPROVED** [review]

**Pull request merged**
