### PR TITLE
Fix for internal/hscan/structmap.go:89:23: undefined: reflect.Pointer

### PR DESCRIPTION
**Pull request by eepurichandra**

### CODE REVIEW

**Review by monkey92t — APPROVED** [review]
OK, we accept this PR, but it is recommended to upgrade go1.18 above versions.

**Comment by Shirtiny** [comment]
> 

I really want to upgrade to Go 1.18, but some cloud platforms only support Go 1.7, and it makes me cry.

**Comment by monkey92t** [comment]
> > 
> 
> I really want to upgrade to Go 1.18, but some cloud platforms only support Go 1.7, and it makes me cry.

wt?  1.7?

**Comment by Shirtiny** [comment]
> > > 
> > 
> > 
> > I really want to upgrade to Go 1.18, but some cloud platforms only support Go 1.7, and it makes me cry.
> 
> wt? 1.7?

1.17

**Comment by monkey92t** [comment]
We only support the 2 latest go versions in most cases, which is also the practice of many go libraries.

**Pull request merged**
