### PR TITLE
Add support for CLIENT NO-EVICT

### LINKED ISSUE #2385: Add support for CLIENT NO-EVICT command
Redis CLIENT NO-EVICT command was added in version 7.0.0 and is currently supported by the library. We should add support as documented [here](https://redis.io/commands/CLIENT-NO-EVICT).

### PR DESCRIPTION
**Pull request by SoulPancake**
fixes #2385

### CODE REVIEW

**Comment by SoulPancake** [comment]
@monkey92t 
Here's the implementation
Followed the same standard followed by Jedis.

**Comment by monkey92t** [comment]
`client-eviction` is not just a command, it is a state of the client connection, targeting a single network connection rather than the entire client.

See: https://redis.io/docs/reference/clients/

**Comment by monkey92t** [comment]
This requires a complicated implementation. Initially we can set it at initialization. If we want to change during the client life cycle, we need to record its state for each network connection.

**Comment by SoulPancake** [comment]
Understood, I'll be closing this
Will understand the problem statement better to tackle this later.

**Pull request closed without merging**
