### PR TITLE
Speed up connections by sending SetInfo via a pipeline

### PR DESCRIPTION
**Pull request by ofekshenawa**

### CODE REVIEW

**Comment by chayim** [comment]
part of #2850

**Review by chayim — APPROVED** [review]

**Comment by git-hulk** [comment]
@ofekshenawa @chayim This will break users using Redis version < 7.2 which doesn't support the `CLIENT SETINFO` command. The previous version works well since the command error was ignored, bringing them into the pipeline will throw an error.

BTW, I think it'd be better to set `DisableIndentity` to `true` by default, for the sake of 7.2 is too new to most users. I will be happy to send a PR to resolve this if it sounds good to you!

**Comment by svenwltr** [comment]
Hello! This was released in a minor update release, but it would break all our apps, since we are using KeyDB and as far as I see it does not support `CLIENT SETINFO`.

Looking at the references to this PR, we are not the only ones having issues.

Are there plans for fixing this or workarounds available?

**Comment by homme** [comment]
Follow #2911 if you've found your way here because this change is breaking your apps.

**Pull request merged**
