### PR TITLE
feat: Add support for CLUSTER SHARDS command

### PR DESCRIPTION
**Pull request by VUHAILAM**
Resolved issue: https://github.com/redis/go-redis/issues/2387

### CODE REVIEW

**Comment by VUHAILAM** [comment]
I need help for writing tests

**Comment by monkey92t** [comment]
We should first create the golang struct according to redis-doc.
Then the redis response data should be read correctly, the following is an example of the response data (RESP3):

*3
%2
$5
slots
*2
:5000
:9999
$5
nodes
*2
%7
$2
id
$40
1b7576ef70dc1db3505ee95a915f8d852d935cc0
$4
port
:8221
$2
ip
$9
127.0.0.1
$8
endpoint
$9
127.0.0.1
$4
role
$6
master
$18
replication-offset
:10677
$6
health
$6
online
%7
$2
id
$40
398f48c467b9a615e847084211d073be719567ce
$4
port
:8224
$2
ip
$9
127.0.0.1
$8
endpoint
$9
127.0.0.1
$4
role
$7
replica
$18
replication-offset
:10677
$6
health
$6
online
%2
$5
slots
*2
:10000
:16383
$5
nodes
*2
%7
$2
id
$40
e072b4419fffdc7242a9ef9c6856715b62cb2eb2
$4
port
:8222
$2
ip
$9
127.0.0.1
$8
endpoint
$9
127.0.0.1
$4
role
$6
master
$18
replication-offset
:23145
$6
health
$6
online
%7
$2
id
$40
57eb082d7872a5322dde1ca484f2c72d2865453d
$4
port
:8225
$2
ip
$9
127.0.0.1
$8
endpoint
$9
127.0.0.1
$4
role
$7
replica
$18
replication-offset
:23131
$6
health
$6
online
%2
$5
slots
*2
:0
:4999
$5
nodes
*2
%7
$2
id
$40
dc69e81b72b33fb31b3d103aec821150a329f2b9
$4
port
:8220
$2
ip
$9
127.0.0.1
$8
endpoint
$9
127.0.0.1
$4
role
$6
master
$18
replication-offset
:10024
$6
health
$6
online
%7
$2
id
$40
e049484178dbb7afc15ede70fc1a59d28d6c3e69
$4
port
:8223
$2
ip
$9
127.0.0.1
$8
endpoint
$9
127.0.0.1
$4
role
$7
replica
$18
replication-offset
:10010
$6
health
$6
online

**Comment by SoulPancake** [comment]
@VUHAILAM Are you still working on this ?

**Comment by VUHAILAM** [comment]
@SoulPancake Oh, sorry. I have some business :( :( If you want to work on it, please go ahead. Thank you!!

**Pull request closed without merging**
