### PR TITLE
test: redis-version to 7.2-rc1

### PR DESCRIPTION
**Pull request by monkey92t**

### CODE REVIEW

**Comment by monkey92t** [comment]
In the redis:latest image, the ENV REDIS_VERSION=7.0.10 version is used.

I corrected the mirror version: redis:7.2-rc

**Review by SoulPancake — APPROVED** [review]
LGTM

**Comment by SoulPancake** [comment]
Can we merge this? @monkey92t For proceeding with the other PRs for version 7.2

**Comment by SoulPancake** [comment]
Any updates on this ? @monkey92t

**Review by vmihailenco — APPROVED** [review]

**Pull request merged**
