### PR TITLE
fix node routing in slotClosestNode

### PR DESCRIPTION
**Pull request by srikar-jilugu**

### CODE REVIEW

**Comment by srikar-jilugu** [comment]
@monkey92t please review this fix for the issue:https://github.com/redis/go-redis/issues/3023

**Review by monkey92t — APPROVED** [review]
Good, but using the nearest node each time will put a lot of stress on that node. We can optimize it further later.

**Comment by srikar-jilugu** [comment]
@monkey92t when can we expect the next release?

**Comment by monkey92t** [comment]
> @monkey92t when can we expect the next release?

v9.5.3

**Comment by srikar-jilugu** [comment]
> v9.5.3

@monkey92t this release doesn't include commits of this pr

**Comment by monkey92t** [comment]
> > v9.5.3
> 
> @monkey92t this release doesn't include commits of this pr

Changes

- Support Hash-field expiration for 7.4 CE RC2 (https://github.com/redis/go-redis/pull/3040)
- **fix node routing in slotClosestNode (https://github.com/redis/go-redis/pull/3043)**
.....

???

**Comment by srikar-jilugu** [comment]
https://github.com/redis/go-redis/blob/f752b9a9d5cc158381c2ffe5b13c531037426b39/osscluster.go#L732

The commits are there in master branch, but the release seems to be behind it

**Comment by srikar-jilugu** [comment]
https://github.com/redis/go-redis/compare/v9.5.2...v9.5.3

**Comment by monkey92t** [comment]
It seems to have been affected. I'll take a look.

**Comment by monkey92t** [comment]
@srikar-jilugu I've added a new version. v9.5.4

**Comment by srikar-jilugu** [comment]
> @srikar-jilugu I've added a new version. v9.5.4

Thankyou!

**Pull request merged**
