### PR TITLE
Added test case for CLIENT KILL with MAXAGE option

### LINKED ISSUE #2920: Add command filter for CLIENT KILL to support maximum age via [MAXAGE] option
As documented [here](https://github.com/redis/redis/pull/12299), to be tested against redis unstable.

### PR DESCRIPTION
**Pull request by vladvildanov**
Closes #2920

### CODE REVIEW

**Review by monkey92t — COMMENTED** [review]
Here, we need to change the test Redis version to the unstable branch.

https://github.com/redis/redis/tree/unstable

**Comment by monkey92t** [comment]
The parameter has not been released in the stable version.

**Comment by vladvildanov** [comment]
@monkey92t Yeah, I got it. I'll work on this 👌

**Review by ofekshenawa — APPROVED** [review]

**Comment by vladvildanov** [comment]
@ofekshenawa Does tests fails because not supported or any other reason?

**Comment by ofekshenawa** [comment]
@vladvildanov yes, currently it's not supported.

**Pull request merged**
