### PR TITLE
test: update go mod before testing(go mod tidy)

### PR DESCRIPTION
**Pull request by monkey92t**

### CODE REVIEW

**Comment by vmihailenco** [comment]
Sometimes updating the dependencies will break the build which can be annoying if all you want is to run the tests...

**Comment by monkey92t** [comment]
> Sometimes updating the dependencies will break the build which can be annoying if all you want is to run the tests...

#2420 #2421

**Comment by monkey92t** [comment]
@vmihailenco We need to update go.sum in order to run the tests.

**Comment by vmihailenco** [comment]
@monkey92t alright, I did not realize that. Could you change `make go_mod_tidy` to not run `go get -u` and make a separate command like `make update_deps` that updates dependencies? Then we can merge this.

**Comment by monkey92t** [comment]
It seems that we only need to run `go mod tidy` when `make test`.

**Review by vmihailenco — APPROVED** [review]

**Pull request merged**
