### PR TITLE
Add support for BLMPOP

### PR DESCRIPTION
**Pull request by yikuaibro**
@monkey92t  I'm learning from LMPOP, so I tried adding the BLMPOP command.  Please help to review whether this PR meets the requirements of the BLMPOP command.
Fix: #2383

### CODE REVIEW

**Comment by monkey92t** [comment]
I am reflecting on whether the setting of `ListElementCmd` is correct, wait for a while.

**Comment by yikuaibro** [comment]
> I am reflecting on whether the setting of `ListElementCmd` is correct, wait for a while.

OK

**Comment by yikuaibro** [comment]
> @yikuaibro pull master, link #2443

Got it.

**Comment by yikuaibro** [comment]
I have fixed it.

**Review by monkey92t — APPROVED** [review]

**Pull request merged**
