### PR TITLE
Support for CLIENT SETINFO

### LINKED ISSUE #2654: Clients should identify themselves on connect
[CLIENT SETINFO](https://redis.io/commands/client-setinfo/) is a new fire-and-forget command that is available as part of redis 7.2. Clients should send the lowercased version of the client name (i.e redis-py, jedis, go-redis) as part of the initial connect, after authenticating to the server.

### PR DESCRIPTION
**Pull request by SoulPancake**
- Fixes #2654

### CODE REVIEW

**Comment by chayim** [comment]
@ofekshenawa thought you should take a look given what we'd discussed.

**Comment by ofekshenawa** [comment]
@SoulPancake LGTM!
Thank you for your contribution.

**Review by ofekshenawa — APPROVED** [review]

**Comment by monkey92t** [comment]
@SoulPancake 

redis.doc: `The CLIENT SETINFO command assigns various info attributes to the current connection which are displayed in the output of [CLIENT LIST](https://redis.io/commands/client-list) and [CLIENT INFO](https://redis.io/commands/client-info).`

As described in the Redis documentation, it represents the state of a network connection rather than just a simple command.

**Comment by monkey92t** [comment]
We should invoke this method during connection initialization and ignore failures (for versions < 7.2) link:

https://github.com/redis/go-redis/issues/2654#issuecomment-1651073598

**Pull request merged**
