### PR TITLE
retract v9.5.3 of redisotel and other extra packages

### PR DESCRIPTION
**Pull request by ipechorin**

### CODE REVIEW

**Comment by hafkensite** [comment]
https://github.com/redis/go-redis/blob/1da50b33ef44c54143b194edcba664d7503b8fc9/go.mod also retracts v9.5.4

**Comment by ipechorin** [comment]
> https://github.com/redis/go-redis/blob/1da50b33ef44c54143b194edcba664d7503b8fc9/go.mod also retracts v9.5.4

As far as I could find, v9.5.4 was never released (tagged) for the extra packages? Or did I miss something

**Comment by hafkensite** [comment]
> > https://github.com/redis/go-redis/blob/1da50b33ef44c54143b194edcba664d7503b8fc9/go.mod also retracts v9.5.4
> 
> As far as I could find, v9.5.4 was never released (tagged) for the extra packages? Or did I miss something

That could very well be, didn't verify that. :+1:

**Review by hafkensite — APPROVED** [review]
LGTM

**Comment by ipechorin** [comment]
@ofekshenawa could you please review this PR?

**Review by vladvildanov — APPROVED** [review]

**Comment by vladvildanov** [comment]
@ipechorin Thanks for this contribution, we totally missed sub-modules

**Pull request merged**
